name: A workflow to test the composite action
on: [workflow_dispatch]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Run composite greeting action
        uses: jpedro1711/github-actions-course/.github/actions/composite-cache-deps@v1.0
        with:
          who-to-greet: 'Alice'
